### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by sannykr** [conda-forge/phosphor-feedstock#1]
@dougalsutherland : although the whole source code has been packaged, I am unable to install it using "conda install -c conda-forge phosphor".  
nodejs is on conda-forge, and looks like that can be installed using conda install.
Could you please suggest something so that conda install works with phorphor as well.

**Comment by djsutherland** [comment]
I just tried, and it works for me. Going to need more specifics than "unable to install it" to be able to help.

**Comment by sannykr** [comment]
After executing "conda install -c conda-forge phosphor", when I tried to test the installation using "npm list -g phosphor", it says that phosphor is not installed.
I also looked into the folder .node-modules-global, and couldn't find the phosphor installed.

But, when I used "conda list phosphor", I found that it is installed at /Users/sannykumar/miniconda/pkgs/phosphor-0.7.1-0/lib/node_modules/

**Comment by djsutherland** [comment]
Make sure you're using the right `npm`. It works for me:

```
$ npm list -g phosphor
/Users/dougal/anaconda/envs/py3/lib
└── phosphor@0.7.1
```

**Comment by sannykr** [comment]
@dougalsutherland : Thanks. Probably I was not using the right npm, that's why it was looking at the  wrong path. Things have been resolved now.
